version: 1.1.{build}
skip_tags: true
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
services:
  - mssql2014
  - postgresql

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/
  
before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build ./IdentityBase.sln -c Release /property:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - nuget pack ./src/IdentityBase/IdentityBase.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  
test_script:
  - bash coveralls.sh
  
artifacts:
  - path: artifacts\**\*.*